[Server]
hostname = "localhost"      # Domain / IP adresiniz varsa buraya yazabilirsiniz (Örn: "192.168.1.100")
title = "Bursa Merkez Nitter"
address = "0.0.0.0"
port = 8080
https = false                # HTTPS kullanmıyorsanız çerezlerin çalışması için false olmalı
httpMaxConnections = 100
staticDir = "./public"

[Cache]
listMinutes = 240            # Listelerin önbellek süresi (dakika)
rssMinutes = 10              # RSS akışlarının önbellek süresi (dakika)
redisHost = "redis"          # Docker-compose içindeki redis servisinin adı
redisPort = 6379
redisPassword = ""
redisConnections = 20
redisMaxConnections = 30

[Config]
hmacKey = "bursamerkezi_gizli_anahtar_987654"  # Güvenli video imzaları oluşturmak için rastgele anahtar
base64Media = false
enableRSS = true             # RSS beslemelerinin çalışması için aktif olmalı
enableRSSUserTweets = true
enableRSSUserReplies = true
enableRSSUserMedia = true
enableRSSSearch = true
enableRSSList = true
enableDebug = false
proxy = ""                   # IP engellemesi yaşamamak için dilerseniz bir proxy ekleyebilirsiniz
proxyAuth = ""
apiProxy = ""
disableTid = false
maxConcurrentReqs = 10
maxRetries = 3
retryDelayMs = 150

[Preferences]
theme = "Nitter"
replaceTwitter = "localhost:8088"
replaceYouTube = "piped.video"
replaceReddit = "teddit.net"
proxyVideos = true           # ÖNEMLİ: Videoların sorunsuz oynatılması için Nitter üzerinden proxy'lenmesi gerekir
hlsPlayback = false          # Native MP4 kullanımı için kapalı durabilir
infiniteScroll = false
